config/routes.rb
Rails.application.routes.draw do
  resources :add_fields_to_drugstores
  resources :add_fields_to_drugstore_medicines
  get 'checkout/:id', to: 'checkout#index', as: 'checkout'
  get 'checkout/done/:id', to: 'checkout#done', as: 'checkout_done'
  get 'patients/my_medicines'
  get 'promotion/index'
  get 'chats/index'
  get 'rainbow/index'
  mount RailsAdmin::Engine => '/cafe', as: 'rails_admin'
  devise_for :admins
  resources :admins
  root 'home#index'
  devise_for :doctors
  devise_for :patients
  resources :drugstore_medicines
  resources :drugstores
  resources :doctor_prescriptions
  resources :medicines
  resources :doctors
  resources :hospitals
  resources :patients
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :hospital
end

app/models/drugstore.rb
class Drugstore < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/drugstore_medicine.rb
class DrugstoreMedicine < ApplicationRecord
  belongs_to :drugstore
  belongs_to :medicine

  validates :price, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  mount_uploader :medicine, MedicineUploader
  validates :name, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name, class_name = nil)
    if params[:controller] == controller_name
     class_name == nil ? "active" : class_name
    else
     nil
    end
  end

  def is_active_controller_action(controller_name, action_name)
    if params[:controller] == controller_name && params[:action] == action_name
      "active"
    else
      nil
    end
  end

  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/drugstores_helper.rb
module DrugstoresHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/promotion_helper.rb
module PromotionHelper
end

app/helpers/rainbow_helper.rb
module RainbowHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/shared/_btn_group_crud.html.erb
<div class="btn-group">
  <button data-toggle="dropdown" class="btn btn-primary btn-xs dropdown-toggle">Opções <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to model do %>
        <i class="fa fa-eye"></i> <%= t('show') %>
      <% end %>
    </li>
      <li>
        <%= link_to path_edit do %>
          <i class="fa fa-pencil"></i> <%= t('edit') %>
        <% end %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to model, method: :delete, data: { confirm: t('you_are_sure?') } do %>
          <i class="fa fa-trash"></i> <%= t('delete') %>
        <% end %>
      </li>
  </ul>
</div>

app/views/shared/_btn_single.html.erb
<% label = t('show') if label.nil? %>
<%= link_to label, link_to, class: 'btn btn-primary btn-xs' %>

app/views/shared/_datatable.html.erb
<% order_by = 0 unless order_by %>
<% order = 'asc' unless order %>

<script type="text/javascript">
$(function() {
    $('.datatable').DataTable({
        "language": {"url": "/datatable-<%= I18n.locale %>.lang"},
        order: [[ '<%= order_by %>', '<%= order %>' ]],
        pageLength: 25,
        responsive: true
    });
});
</script>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('error_to_save') %></h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_page_heading.html.erb
<br><br>

<!--<div class="row wrapper border-bottom white-bg page-heading">-->
<!--  <div class="col-sm-4">-->
<!--    <h2><%= t(controller_name).titleize %></h2>-->
<!--    <ol class="breadcrumb">-->
<!--      <li class="active">-->
<!--        <strong><%= t(action_name).titleize %></strong>-->
<!--      </li>-->
<!--    </ol>-->
<!--  </div>-->
<!--</div>-->
<!--<br>-->

app/views/shared/datatable_complet.html.erb
<% order_by = 0 unless order_by %>
<% order = 'asc' unless order %>

<script type="text/javascript">
$(function() {
    $('.datatable').DataTable({
        "language": {"url": "/datatable-<%= I18n.locale %>.lang"},
        order: [[ '<%= order_by %>', '<%= order %>' ]],
        pageLength: 25,
        responsive: true,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {text: '<%= t('copy') %>', extend: 'copy'},
            {extend: 'csv', title: '<%= name %>', exportOptions: {columns: ':visible:not(.not-export-col)'}},
            {extend: 'excel', title: '<%= name %>', exportOptions: {columns: ':visible:not(.not-export-col)'}},
            {extend: 'pdf', title: '<%= name %>', exportOptions: {columns: ':visible:not(.not-export-col)'}},
            {extend: 'print', exportOptions: {columns: ':visible:not(.not-export-col)'},
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table').addClass('compact').css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>