config/routes.rb
Rails.application.routes.draw do
  resources :add_fields_to_drugstores
  resources :add_fields_to_drugstore_medicines
  get 'checkout/:id', to: 'checkout#index', as: 'checkout'
  get 'checkout/done/:id', to: 'checkout#done', as: 'checkout_done'
  get 'patients/my_medicines'
  get 'promotion/index'
  get 'chats/index'
  get 'rainbow/index'
  mount RailsAdmin::Engine => '/cafe', as: 'rails_admin'
  devise_for :admins
  resources :admins
  root 'home#index'
  devise_for :doctors
  devise_for :patients
  resources :drugstore_medicines
  resources :drugstores
  resources :doctor_prescriptions
  resources :medicines
  resources :doctors
  resources :hospitals
  resources :patients
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :hospital
end

app/models/drugstore.rb
class Drugstore < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/drugstore_medicine.rb
class DrugstoreMedicine < ApplicationRecord
  belongs_to :drugstore
  belongs_to :medicine

  validates :price, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  mount_uploader :medicine, MedicineUploader
  validates :name, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if patient_signed_in?
      @prescriptions = DoctorPrescription.where(patient: current_patient)
      render :patient
    elsif doctor_signed_in?
      render :doctor
    elsif admin_signed_in?
      render :admin
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name, class_name = nil)
    if params[:controller] == controller_name
     class_name == nil ? "active" : class_name
    else
     nil
    end
  end

  def is_active_controller_action(controller_name, action_name)
    if params[:controller] == controller_name && params[:action] == action_name
      "active"
    else
      nil
    end
  end

  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/drugstores_helper.rb
module DrugstoresHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/promotion_helper.rb
module PromotionHelper
end

app/helpers/rainbow_helper.rb
module RainbowHelper
end

app/views/home/admin.html.erb
<div class="row">
  <div class="col-lg-3 animated bounceIn">
    <%= link_to rails_admin_path do %>
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-lock fa-5x" aria-hidden="true"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Administração</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/doctor.html.erb
<div class="row">
  <div class="col-lg-3 animated bounceIn">
    <%= link_to "" do %>
      <div class="widget style1 gray-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Chat</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-3 animated bounceIn">
    <%= link_to "" do %>
      <div class="widget style1 gray-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-phone fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Ligação</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-3 animated bounceIn">
    <%= link_to "" do %>
      <div class="widget style1 gray-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-desktop fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Vídeo Chamada</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-3 animated bounceIn">
    <%= link_to "/doctors" do %>
      <div class="widget style1 red-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-file-text fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Prescrições</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-3 animated bounceIn">
    <%= link_to "" do %>
      <div class="widget style1 red-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-address-book fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Farmácias</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-3 animated bounceIn">
    <%= link_to "" do %>
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-money fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Promoções</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1 align="center">Escolha seu perfil</h1>

<div class="row">
  <div class="col-lg-3 animated bounceIn">
    <%= link_to new_patient_session_path do %>
      <div class="widget style1 navy-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Paciente</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-3 animated bounceIn">
    <%= link_to new_doctor_session_path do %>
      <div class="widget style1 red-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-address-book fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Médico</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-3 animated bounceIn">
    <%= link_to new_doctor_session_path do %>
      <div class="widget style1 yellow-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-money fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Farmácia</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="col-lg-3 animated bounceIn">
    <%= link_to new_admin_session_path do %>
      <div class="widget style1 gray-bg">
        <div class="row">
          <div class="col-xs-4">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
            <span>Admin</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/patient.html.erb
<div class="ibox-content animated fadeInRightBig">
  <table class="table table-striped table-bordered table-hover datatable">
    <thead>
      <tr>
        <th>Médico</th>
        <th>Medicamento</th>
        <th>Dosagem</th>
        <th width="1%" class="not-export-col"></th>
      </tr>
    </thead>
    <tbody>
      <% @prescriptions.each do |prescription| %>
        <tr>
          <td><%= prescription.doctor.name %></td>
          <td><%= prescription.medicine.name %></td>
          <td><%= prescription.dosage %></td>
          <td align="center"><%= render 'shared/btn_single', link_to: prescription %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'shared/datatable', name: 'Minhas prescrições' %>