config/routes.rb
Rails.application.routes.draw do
  resources :add_fields_to_drugstores
  resources :add_fields_to_drugstore_medicines
  get 'checkout/:id', to: 'checkout#index', as: 'checkout'
  get 'checkout/done/:id', to: 'checkout#done', as: 'checkout_done'
  get 'patients/my_medicines'
  get 'promotion/index'
  get 'chats/index'
  get 'rainbow/index'
  mount RailsAdmin::Engine => '/cafe', as: 'rails_admin'
  devise_for :admins
  resources :admins
  root 'home#index'
  devise_for :doctors
  devise_for :patients
  resources :drugstore_medicines
  resources :drugstores
  resources :doctor_prescriptions
  resources :medicines
  resources :doctors
  resources :hospitals
  resources :patients
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/add_fields_to_drugstore.rb
class AddFieldsToDrugstore < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :hospital
end

app/models/drugstore.rb
class Drugstore < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/drugstore_medicine.rb
class DrugstoreMedicine < ApplicationRecord
  belongs_to :drugstore
  belongs_to :medicine

  validates :price, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  validates :name, presence: true
  validates :phone, presence: true
  validates :cep, presence: true
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  mount_uploader :medicine, MedicineUploader
  validates :name, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/add_fields_to_drugstores_controller.rb
class AddFieldsToDrugstoresController < ApplicationController
  before_action :set_add_fields_to_drugstore, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @add_fields_to_drugstores = AddFieldsToDrugstore.all
    respond_with(@add_fields_to_drugstores)
  end

  def show
    respond_with(@add_fields_to_drugstore)
  end

  def new
    @add_fields_to_drugstore = AddFieldsToDrugstore.new
    respond_with(@add_fields_to_drugstore)
  end

  def edit
  end

  def create
    @add_fields_to_drugstore = AddFieldsToDrugstore.new(add_fields_to_drugstore_params)
    @add_fields_to_drugstore.save
    respond_with(@add_fields_to_drugstore)
  end

  def update
    @add_fields_to_drugstore.update(add_fields_to_drugstore_params)
    respond_with(@add_fields_to_drugstore)
  end

  def destroy
    @add_fields_to_drugstore.destroy
    respond_with(@add_fields_to_drugstore)
  end

  private
    def set_add_fields_to_drugstore
      @add_fields_to_drugstore = AddFieldsToDrugstore.find(params[:id])
    end

    def add_fields_to_drugstore_params
      params.require(:add_fields_to_drugstore).permit(:street, :city, :state, :number)
    end
end

app/helpers/add_fields_to_drugstores_helper.rb
module AddFieldsToDrugstoresHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active_controller(controller_name, class_name = nil)
    if params[:controller] == controller_name
     class_name == nil ? "active" : class_name
    else
     nil
    end
  end

  def is_active_controller_action(controller_name, action_name)
    if params[:controller] == controller_name && params[:action] == action_name
      "active"
    else
      nil
    end
  end

  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/drugstores_helper.rb
module DrugstoresHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/promotion_helper.rb
module PromotionHelper
end

app/helpers/rainbow_helper.rb
module RainbowHelper
end

app/views/add_fields_to_drugstores/_form.html.erb
<%= form_with(model: add_fields_to_drugstore, local: true) do |form| %>
  <% if add_fields_to_drugstore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_fields_to_drugstore.errors.count, "error") %> prohibited this add_fields_to_drugstore from being saved:</h2>

      <ul>
      <% add_fields_to_drugstore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/add_fields_to_drugstores/edit.html.erb
<h1>Editing Add Fields To Drugstore</h1>

<%= render 'form', add_fields_to_drugstore: @add_fields_to_drugstore %>

<%= link_to 'Show', @add_fields_to_drugstore %> |
<%= link_to 'Back', add_fields_to_drugstores_path %>

app/views/add_fields_to_drugstores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add Fields To Drugstores</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_fields_to_drugstores.each do |add_fields_to_drugstore| %>
      <tr>
        <td><%= add_fields_to_drugstore.street %></td>
        <td><%= add_fields_to_drugstore.city %></td>
        <td><%= add_fields_to_drugstore.state %></td>
        <td><%= add_fields_to_drugstore.number %></td>
        <td><%= link_to 'Show', add_fields_to_drugstore %></td>
        <td><%= link_to 'Edit', edit_add_fields_to_drugstore_path(add_fields_to_drugstore) %></td>
        <td><%= link_to 'Destroy', add_fields_to_drugstore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add Fields To Drugstore', new_add_fields_to_drugstore_path %>

app/views/add_fields_to_drugstores/new.html.erb
<h1>New Add Fields To Drugstore</h1>

<%= render 'form', add_fields_to_drugstore: @add_fields_to_drugstore %>

<%= link_to 'Back', add_fields_to_drugstores_path %>

app/views/add_fields_to_drugstores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @add_fields_to_drugstore.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @add_fields_to_drugstore.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @add_fields_to_drugstore.state %>
</p>

<p>
  <strong>Number:</strong>
  <%= @add_fields_to_drugstore.number %>
</p>

<%= link_to 'Edit', edit_add_fields_to_drugstore_path(@add_fields_to_drugstore) %> |
<%= link_to 'Back', add_fields_to_drugstores_path %>